- hosts: worker-chechssd7
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_hostname

    - name: Create workspace directory
      file:
        path: '{{ workspace }}'
        state: directory

    - name: Copy check script to remote server
      copy:
        src: '{{ workspace }}/checkssd7.sh'
        dest: '{{ workspace }}'
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: +x

    - name: Worker pre check
      shell: '{{ workspace }}/checkssd7.sh'
      register: check_result

    - name: Echo check result
      debug:
        msg: '{{ check_result.stdout }}'
