- hosts: worker-bench
  remote_user: '{{ remote_user }}'
  environment:
    RUST_LOG: '{{ rust_log }}'
    RUST_BACKTRACE: '{{ rust_backtrace }}'
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_parameter_cache }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    FIL_PROOFS_USE_MULTICORE_SDR: '{{ fil_proofs_use_multicore_sdr }}'
    FIL_PROOFS_MULTICORE_SDR_PRODUCERS: 1
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses[1]
    - debug: var=ansible_hostname

    - name: Start benchmark
      shell: |
        tmux new -s lotus -d -n bench
        tmux send-keys -t lotus:bench "export ENV_CPU_CORE_BEGIN_NUM=0" C-m
        tmux send-keys -t lotus:bench "export ENV_CPU_CORE_END_NUM=8" C-m
        tmux send-keys -t lotus:bench "lotus-bench sealing --sector-size 32GiB --skip-unseal --storage-dir /home/caslx/disk_md0 --skip-commit2 true --skip-unseal true" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/bench-`date +%Y-%m-%d-%H-%M`.log"