- hosts: 10.0.1.106
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - debug: var=ansible_all_ipv4_addresses

    - name: update_space
      shell: |




             i


















          'chown caslx:caslx /home/caslx/workspace'
